In [13]:
import numpy as np
import matplotlib.pyplot as plt

In [18]:
# 1-D array of ints
a = np.array([1,2,3])
print(a)
a.ndim
a.shape

[1 2 3]


(3,)

In [19]:
# 2-D array of floats — in this case, a list within a list
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)
b.ndim
b.shape

[[9. 8. 7.]
 [6. 5. 4.]]


(2, 3)

In [20]:
# 3-D array of ints — three lists inside a list
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
c.ndim
c.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [28]:
# get type and size of arrays
a.dtype

dtype('int64')

In [27]:
# get size
a.itemsize

8

In [31]:
# get total size (nbytes = itemsize * size)
a.nbytes

24

Accessing and changes specific elements, rows, cols, etc.

In [34]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [42]:
# get specific element [r, c] (recall it uses 0-indexing) (can use negative indexing like in lists {-1 gets the last element, for example})
a[1, 5]


np.int64(13)

In [46]:
# get a specific row (the first one) // a[0] also works
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [59]:
# get a spefici col
a[:, 2]

array([ 3, 10])

In [60]:
# [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [66]:
a[:, 2] = 99
a

array([[ 1,  2, 99,  4,  5,  6,  7],
       [ 8,  9, 99, 11, 12, 99, 14]])

3-D example

In [69]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [74]:
# get specific element (work ouside in — look for the 4) (so target the first set, then the row, then the col)
b[0,1,1]

np.int64(4)

In [77]:
# get the first row from both arrays (:,0,: means "all dimensions, first row, all cols" in the DRC framework)
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [ ]:
# get the second row from both arrays
b[:,1,:]

In [78]:
# replace a specific element (in this case, the 6)
b[1,0,1] = 99
print(b)

[[[ 1  2]
  [ 3  4]]

 [[ 5 99]
  [ 7  8]]]
